language: python

python: 3.4

sudo: false

services:
    - mongodb
    - elasticsearch
    - redis-server

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
    - unixodbc
    - unixodbc-dev
    - freetds-dev
    - freetds-bin
    - tdsodbc

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm

before_install:
    - nvm install node
    - nvm use node
    - node --version
    - npm install -g npm@latest
    - npm install -g grunt-cli
    - pip install requests
    - export DISPLAY=:99.0
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24
    - ./scripts/get-chrome-url | wget -N --no-verbose -i -
    - unzip chrome-linux.zip
    - export CHROME_BIN=`pwd`/chrome-linux/chrome
    - $CHROME_BIN --version

install:
    - cd server && pip install -r dev-requirements.txt && cd ..
    - cd client && npm install --python=python2.7 && cd ..

script:
    - cd client && npm test && cd ..
    - cd server && flake8 && cd ..
    - cd server && time behave ./features/ --format progress2 --logging-level ERROR && cd ..
    - cd server && time nosetests && cd ..
    - cd client && grunt build && cd ..
    - cd server && python manage.py users:create -u test -p test -e test@localhost --admin && cd ..

after_script:
    - rm .npm/*.lock
